---
# tasks file for fail2ban
- name: Install fail2ban and systemd-dependency
  ansible.builtin.package:
    name: 
      - python3-systemd
      - fail2ban
    state: present
  become: true

- name: Copy jail.local
  ansible.builtin.copy:
    src: etc/fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Enable and start fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true
  become: true


