---
# tasks file for docker
- name: Install requirements for docker
  ansible.builtin.package:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present
  become: true

- name: Add gpg key for repository
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present
  become: true

- name: Add docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: docker
    state: present
  become: true

- name: Install docker
  ansible.builtin.package:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
  notify: Enable and start Docker

